# Generated by Django 2.1.3 on 2018-12-01 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular job', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('descriptoin', models.TextField(help_text='Enter a brief description of the company.', max_length=1000, null=True)),
                ('emp_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular job', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('deadline', models.DateField(null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the job offer.', max_length=1000)),
                ('date_posted', models.DateField(default=datetime.datetime(2018, 12, 1, 11, 8, 7, 180755, tzinfo=utc))),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
