# Generated by Django 2.1.3 on 2018-12-01 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181201_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2018, 12, 1, 12, 14, 0, 794543, tzinfo=utc)),
        ),
    ]
