# Generated by Django 2.1.3 on 2018-12-01 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181201_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='descriptoin',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the company.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2018, 12, 1, 13, 38, 42, 824191, tzinfo=utc)),
        ),
    ]
